### basic settings

# site properties and page defaults
title: Alexandra Vallet
description: academic page of Alexandra Vallet
logo: images/logo.png
header: images/background.jpg
footer: images/background.jpg
baseurl: 

# site social media and other links
links:
  email: vallet@math.uio.no
  google-scholar: tlhucdcAAAAJ
  github: alexandravallet
  twitter: Avalletresearch
  youtube: UCI26By0P0pCdfCP0T065yUA

### advanced settings

# automatic citations
auto-cite:
  plugins:
    - name: sources
      input:
        - ../_data/sources.yaml
  output: ../_data/citations.yaml

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null
